import React, { useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';

import { MBButton, MBCard, MBErrorState, MBHeader, MBSkeletonList, MBSyncStatus } from '@/components';
import { useCatalogSettings } from '@/hooks/useCatalogSettings';
import { useExportReport } from '@/hooks/useExportReport';
import { getReportSummary } from '@/services/api/reportsApi';
import type { ReportPeriod } from '@/shared/types/report.types';
import { useNetworkStore } from '@/store/networkStore';
import { useTheme } from '@/theme/ThemeProvider';
import { formatCurrency, formatQty, toNumber } from '@/utils/money';

/**
 * Reports.
 *
 * Figures and files both come from the server. Exports are generated there
 * (it already has exceljs and pdfkit) and shared from the device — building a
 * spreadsheet on a phone would be slower, less capable, and a second
 * implementation of the same totals to keep in step.
 */

const PERIODS: ReadonlyArray<{ key: ReportPeriod; label: string }> = [
  { key: 'daily', label: 'Today' },
  { key: 'weekly', label: 'Week' },
  { key: 'monthly', label: 'Month' },
  { key: 'yearly', label: 'Year' },
];

export function ReportsScreen(): React.ReactElement {
  const theme = useTheme();
  const { currencySymbol } = useCatalogSettings();
  const isOnline = useNetworkStore(s => s.isOnline);
  const [period, setPeriod] = useState<ReportPeriod>('monthly');
  const { exportReport, isExporting, error: exportError } = useExportReport();

  const summary = useQuery({
    queryKey: ['reports', 'summary', 'export-view', period],
    queryFn: () => getReportSummary({ period }),
  });

  const data = summary.data;

  return (
    <View style={[styles.flex, { backgroundColor: theme.colors.bg }]}>
      <MBHeader title="Reports" right={<MBSyncStatus />} />

      <View style={{ padding: theme.layout.screenPad, gap: theme.space.md }}>
        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={{ gap: theme.space.sm }}>
          {PERIODS.map(option => {
            const selected = option.key === period;
            return (
              <Pressable
                key={option.key}
                onPress={() => setPeriod(option.key)}
                accessibilityRole="button"
                accessibilityState={{ selected }}
                style={[
                  styles.chip,
                  {
                    borderRadius: theme.radius.pill,
                    backgroundColor: selected ? theme.colors.primary : theme.colors.surface,
                    borderColor: selected ? theme.colors.primary : theme.colors.border,
                  },
                ]}>
                <Text
                  style={[
                    theme.type.label,
                    { color: selected ? theme.colors.onPrimary : theme.colors.text },
                  ]}>
                  {option.label}
                </Text>
              </Pressable>
            );
          })}
        </ScrollView>
      </View>

      {summary.isPending ? (
        <MBSkeletonList rows={5} />
      ) : summary.isError ? (
        <MBErrorState
          error={summary.error}
          onRetry={() => summary.refetch()}
          retrying={summary.isFetching}
        />
      ) : (
        <ScrollView
          contentContainerStyle={{ padding: theme.layout.screenPad, gap: theme.space.md }}
          refreshControl={
            <RefreshControl
              refreshing={summary.isFetching && !summary.isPending}
              onRefresh={() => summary.refetch()}
              tintColor={theme.colors.primary}
            />
          }>
          <MBCard>
            <Text style={[theme.type.h3, { color: theme.colors.text }]}>
              {data?.from} → {data?.to}
            </Text>
            <DetailRow label="Revenue" value={formatCurrency(data?.totalRevenue, currencySymbol)} />
            <DetailRow
              label="Expenses"
              value={formatCurrency(data?.totalExpenses, currencySymbol)}
            />
            <DetailRow label="Profit" value={formatCurrency(data?.totalProfit, currencySymbol)} />
            <DetailRow
              label="Discount"
              value={formatCurrency(data?.totalDiscount, currencySymbol)}
            />
            <DetailRow label="Orders" value={formatQty(toNumber(data?.totalOrders))} />
            <DetailRow
              label="Average order"
              value={formatCurrency(data?.averageOrderValue, currencySymbol)}
            />
          </MBCard>

          <MBCard>
            <Text style={[theme.type.h3, { color: theme.colors.text }]}>Export</Text>
            <Text style={[theme.type.caption, { color: theme.colors.textMuted }]}>
              Generated by the server and shared from this device.
            </Text>
            <View style={styles.exportRow}>
              <MBButton
                label="Excel"
                onPress={() => exportReport({ type: 'excel', period })}
                loading={isExporting}
                disabled={!isOnline}
                variant="secondary"
                size="sm"
                testID="export-excel"
              />
              <MBButton
                label="PDF"
                onPress={() => exportReport({ type: 'pdf', period })}
                disabled={!isOnline || isExporting}
                variant="secondary"
                size="sm"
                testID="export-pdf"
              />
              <MBButton
                label="CSV"
                onPress={() => exportReport({ type: 'csv', period })}
                disabled={!isOnline || isExporting}
                variant="secondary"
                size="sm"
                testID="export-csv"
              />
            </View>
            {!isOnline ? (
              <Text style={[theme.type.caption, { color: theme.colors.offline }]}>
                Exports need a connection — the file is built on the server.
              </Text>
            ) : null}
            {exportError ? (
              <Text
                accessibilityRole="alert"
                style={[theme.type.caption, { color: theme.colors.danger }]}>
                {exportError}
              </Text>
            ) : null}
          </MBCard>

          {(data?.dailyData ?? []).length > 0 ? (
            <MBCard>
              <Text style={[theme.type.h3, { color: theme.colors.text }]}>Daily</Text>
              {(data?.dailyData ?? []).slice(-14).map(day => (
                <DetailRow
                  key={day.date}
                  label={day.date}
                  value={formatCurrency(day.totalRevenue, currencySymbol)}
                />
              ))}
            </MBCard>
          ) : null}
        </ScrollView>
      )}
    </View>
  );
}

function DetailRow({ label, value }: { label: string; value: string }): React.ReactElement {
  const theme = useTheme();
  return (
    <View style={styles.detailRow}>
      <Text
        style={[theme.type.body, styles.flex, { color: theme.colors.textMuted }]}
        numberOfLines={1}>
        {label}
      </Text>
      <Text style={[theme.type.mono, { color: theme.colors.text }]}>{value}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  chip: {
    height: 36,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  exportRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, paddingTop: 10 },
});
